// app/components/BottomNav.jsx
'use client';

import Link from "next/link";
import { usePathname } from "next/navigation";

const Item = ({ href, label, icon, active }) => (
  <Link
    href={href}
    className={[
      "flex flex-col items-center justify-center w-full h-full",
      active ? "text-brand-600" : "text-gray-500 hover:text-gray-700"
    ].join(" ")}
  >
    <div className={[
      "grid h-10 w-10 place-items-center rounded-2xl border",
      active ? "border-brand-200 bg-brand-50" : "border-gray-200 bg-white"
    ].join(" ")}>
      {icon}
    </div>
    <span className="mt-1 text-[11px]">{label}</span>
  </Link>
);

export default function BottomNav() {
  const p = usePathname() || "/";
  const is = (s) => p === s || p.startsWith(s + "/");

  return (
    <nav
      style={{ height: "var(--tabbar-h)" }}
      className="fixed inset-x-0 bottom-0 z-20 border-t bg-white"
    >
      <div className="mx-auto grid max-w-md grid-cols-5 gap-1 px-2">
        <Item href="/"          label="Home"     active={is("/")}         icon={<HomeIcon />} />
        <Item href="/jobs"      label="Jobs"     active={is("/jobs")}      icon={<BriefcaseIcon />} />
        <Item href="/messages"  label="Messages" active={is("/messages")}  icon={<ChatIcon />} />
        <Item href="/plans"     label="Plans"    active={is("/plans")}     icon={<StarIcon />} />
        <Item href="/profile"   label="Profile"  active={is("/profile")}   icon={<UserIcon />} />
      </div>
    </nav>
  );
}

/* Tiny inline icons to avoid any dependency */
function HomeIcon() { return (<svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5v-9Z" stroke="currentColor" strokeWidth="1.6" /><path d="M9 21v-6h6v6" stroke="currentColor" strokeWidth="1.6" /></svg>); }
function BriefcaseIcon() { return (<svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M3 8.5h18v10a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 18.5v-10Z" stroke="currentColor" strokeWidth="1.6"/><path d="M8 8.5V6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2.5" stroke="currentColor" strokeWidth="1.6"/><path d="M3 12.5h18" stroke="currentColor" strokeWidth="1.6"/></svg>); }
function ChatIcon() { return (<svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M21 13.5a7.5 7.5 0 1 1-3.3-6.2L21 4.5v9Z" stroke="currentColor" strokeWidth="1.6" /><circle cx="9" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="15" cy="12" r="1" fill="currentColor"/></svg>); }
function StarIcon() { return (<svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="m12 3 2.6 5.3 5.9.9-4.2 4.1 1 5.8L12 16.7 6.7 19.1l1-5.8-4.2-4.1 5.9-.9L12 3Z" stroke="currentColor" strokeWidth="1.6"/></svg>); }
function UserIcon() { return (<svg width="18" height="18" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="7.5" r="3.5" stroke="currentColor" strokeWidth="1.6"/><path d="M4.5 20a7.5 7.5 0 0 1 15 0" stroke="currentColor" strokeWidth="1.6"/></svg>); }

// frontend/src/components/BottomNav.vue
<script setup>
import { RouterLink, useRoute } from 'vue-router';

const props = defineProps({
  items: {
    type: Array,
    default: () => []
  }
});

const route = useRoute();

function isActive(item) {
  if (!item) return false;
  if (item.exact) {
    return route.path === item.to;
  }
  return route.path.startsWith(item.to);
}
</script>

<template>
  <nav
    v-if="items.length"
    class="fixed bottom-0 left-0 right-0 z-40 border-t border-slate-200 bg-white/95 shadow-lg backdrop-blur md:hidden"
    role="navigation"
    aria-label="Primary navigation"
  >
    <div class="mx-auto flex max-w-6xl items-stretch justify-around px-2 py-2">
      <RouterLink
        v-for="item in items"
        :key="item.to"
        :to="item.to"
        class="flex flex-1 flex-col items-center gap-1 rounded-xl px-2 py-1 text-xs font-semibold transition"
        :class="isActive(item) ? 'text-emerald-600' : 'text-slate-500 hover:text-emerald-600'"
      >
        <svg
          v-if="item.icon === 'home'"
          viewBox="0 0 24 24"
          class="h-6 w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M3 11.25 12 3l9 8.25M5.25 9.75V21h5.25v-5.25h3V21h5.25V9.75" />
        </svg>
        <svg
          v-else-if="item.icon === 'jobs'"
          viewBox="0 0 24 24"
          class="h-6 w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 7.5V6A1.5 1.5 0 0 1 10.5 4.5h3A1.5 1.5 0 0 1 15 6v1.5M5.25 9h13.5a1.5 1.5 0 0 1 1.5 1.5v8.25a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V10.5a1.5 1.5 0 0 1 1.5-1.5Z" />
        </svg>
        <svg
          v-else-if="item.icon === 'messages'"
          viewBox="0 0 24 24"
          class="h-6 w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 1 1-4.219-7.594l3.219-1.156-.917 3.281A8.96 8.96 0 0 1 21 12Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 12h.008v.008H7.5V12Zm4.5 0h.008v.008H12V12Zm4.5 0h.008v.008H16.5V12Z" />
        </svg>
        <svg
          v-else-if="item.icon === 'profile'"
          viewBox="0 0 24 24"
          class="h-6 w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 7.5a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 19.875a8.25 8.25 0 0 1 15 0" />
        </svg>
        <svg
          v-else-if="item.icon === 'admin'"
          viewBox="0 0 24 24"
          class="h-6 w-6"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 21h7.5M4.5 9.75l3 6h9l3-6" />
        </svg>
        <span>{{ item.label }}</span>
      </RouterLink>
    </div>
  </nav>
</template>
